### ISSUE TITLE
Opening /de version also loads english data and vice versa

### ISSUE THREAD

**Issue by gustavorino** [johannesspohr/gatsby-starter-i18next-sanity#2]
Open https://gatsby-starter-i18next-sanity.netlify.app/en and check the network tab.

There is a request loading page-data/de/page-data.json 

And vice-versa for /de.

Is that an issue?

**Comment by johannesspohr** [comment]
This request are just preloading data in case the user clicks on the language selector. So it will load the data for the shops in English, and for the main page in german (because there is a link in the header). You should be able to avoid this by disabling preloading for the link.
